### ISSUE TITLE
RuntimeError: The NVIDIA driver on your system is too old

### ISSUE THREAD

**Issue by sevengo8378** [flatironinstitute/deepblast#151]
Followed the install guide with GPU: https://github.com/flatironinstitute/deepblast/wiki/Installation

Here is my steps:
conda create -n tmvec python=3.9
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
pip3 install faiss-gpu
pip3 install tm-vec

after run tmvec-build-database got this error:
<img width="1407" alt="image" src="https://github.com/flatironinstitute/deepblast/assets/461736/e48ad075-662a-4348-8fec-8e6c70514df9">

my GPU driver info:
<img width="781" alt="image" src="https://github.com/flatironinstitute/deepblast/assets/461736/3d2c33ad-6a4b-4404-9a75-bf060d20917a">

Don't know what went wrong.

**Comment by blackwer** [comment]
I think the issue is that you should use an older version of the cuda _toolkit_ in your conda environment. While the driver is right, modern toolkits won't work with the older drivers. I think the command
`conda install cuda=11.7` should work, though I don't have a conda environment available.

**Comment by sevengo8378** [comment]
thanks @blackwer , with your method I got this error. 
ERROR: Could not find a version that satisfies the requirement cuda==11.7 (from versions: none)
ERROR: No matching distribution found for cuda==11.7

But the idea is right, and finally I solved it this way.
pip3 install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117

**Comment by mortonjt** [comment]
Great! Got that you got this resolved
